name: androidapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  image_picker: ^1.1.2 
  flutter_native_splash: ^2.4.2

flutter_native_splash:
  color: "#ffffff" # Warna background splash screen (hex)
  android: true # Aktifkan splash screen di Android
  ios: true # Aktifkan splash screen di iOS
  fullscreen: true # (Opsional) Buat fullscreen splash screen  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/chese_burger.jpg
    - assets/bigmac.jpg
    - assets/cola.jpg
    - assets/Teh_Botol.jpg
    - assets/Ayam.jpg
    - assets/spicy_ayam.jpg
    - assets/burrito.jpg
    - assets/logo.jpg
    - assets/es_krim.jpg
